eclipse-mosquitto:
  image: eclipse-mosquitto
  container_name: eclipse-mosquitto
  restart: always
  ports:
    - 1883:1883
    - 1884:1884
    # - 9001:9001
  volumes:
    - ./mosquitto.conf:/mosquitto/config/mosquitto.conf